=== josemungu/EjerciciosLMGSI/DragonBall.dtd
<!ELEMENT DragonBall ( personajes,habilidades+,amigos?)*>
<!ELEMENT personajes (personaje)*>
<!ELEMENT habilidades (habilidad)+>
<!ELEMENT amigos (amigo)?>
<!ELEMENT personaje EMPTY>
<!ELEMENT habilidad (#PCDATA | nombreHab)*>
<!ELEMENT amigo EMPTY>
<!ELEMENT nombreHab EMPTY>

<!ENTITY % repetitivo "nombre ID #REQUIRED">
<!ENTITY % similar "personaje IDREF #IMPLIED">

<!ATTLIST personaje %repetitivo;>
<!ATTLIST personajE vida (vivo|muerto) "muerto"
                    fechaNacimiento CDATA #REQUIRED
                     nombre CDATA ID #REQUIRED>

<!ATTLIST habilidades %repetitivo;>
<!ATTLIST habilidades %similar;>
<!ATTLIST habilidad nombre ID #REQUIRED
                    habilidad IDREF #IMPLIED>

<!ATTLIST amigos %repetitivo;>
<!ATTLIST amigos %similar;>
<!ATTLIST amigo nombre ID #REQUIRED>
                amigoCercano IDREF #IMPLIED>

=== josemungu/EjerciciosLMGSI/DragonBall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DragonBall  SYSTEM "DragonBall.dtd">
<DragonBall>
    <personajes>
        <personaje nombre="SonGoku" fechaNacimiento="25/10/2003" vida="muerto"/> 
    </personajes>
    <habilidades>
        <habilidad nombre="SonGoku" habilidad="eer movimientos de rivales">58818</habilidad>
        <habilidad nombre="Vegeta" habilidad= "volar">
            <nombreHab/>
        </habilidad>
        <habilidad nombre="Inteligencia sobrehumana"></habilidad>
    </habilidades>
    <amigos>
        <amigo nombre="Son Goku" amigoCercano="Krilin"></amigo>
        <amigo nombre="Vegeta" amigoCercano="Trunks" ></amigo>
        <amigo nombre= "Bulma" amigoCercano="Vegeta"></amigo>
    </amigos>
</DragonBall>
